### PR TITLE
Comment out assertion that fails during onboarding

### PR DESCRIPTION
**Pull request by syoung-smallwisdom**
This assertion was blocking me from being able to sign in to the CRF app using an existing external ID.

### CODE REVIEW

**Comment by Erin-Mounts** [comment]
This is an assertion because it should never happen. Until you're signed in, the BridgeSDK will give you a dummy SBBStudyParticipant to play with. Is it maybe somehow getting called before BridgeSDK has been set up? FWIW I've successfully signed in to CRF using an existing external ID so it seems like there must be more going on here than just that.

**Comment by syoung-smallwisdom** [comment]
Yup, likely there is. New phone running iOS 11.2. Honestly, didn't spend too much time on it. Let's leave the PR open for now as a marker to revisit.

**Comment by syoung-smallwisdom** [comment]
@Erin-Mounts 
I had this happen again Friday. It appears to be related to trying to run the app on a device or simulator where the keychain has been blown away but there is lingering info in cache. The result is partially signed in user.

This is going to be an issue for any of our longer-running studies where the user may switch phones because the keychain isn't restored. (I had to re-login to everything when I upgraded my phone.)

**Comment by Erin-Mounts** [comment]
I also saw this once on Friday, when I got most of the way through onboarding and then canceled and then tried to go through onboarding again (can’t remember if I quit/killed the app in between or not). I was able to “solve" it by deleting and re-installing but I want to figure out what exactly is getting it into this state. It should never be possible to have a SBBUserSessionInfo object with a nil studyParticipant field but that seems to be what’s happening (and at least the proximal cause of the crash).

**Comment by syoung-smallwisdom** [comment]
Nice to know that I'm not the only one.  :)  And yes, deleting and reinstalling fixed the issue.

**Comment by Erin-Mounts** [comment]
Welp, I was going to try to debug through this and take care of it but I can no longer reproduce it with the latest CRFValidationApp commit in /master.

**Comment by Erin-Mounts** [comment]
It's getting a SBBUserSessionInfo with a nil SBBStudyParticipant field because (a) there's a non-nil SBBUserSessionInfo in CoreData cache but (b) it doesn't have the login credentials anymore, which it needs to decrypt the StudyParticipant from CoreData.

If the app logged out from Bridge, the cache would have been cleared so I'm guessing that when you "cancel" during onboarding after verifying the external ID (the point at which it logs in), it's clearing the keychain but not actually calling BridgeSDK to log you out. Possibly we assumed you wouldn't be logged in until completing onboarding because that's how apps have worked in the past.

**Comment by Erin-Mounts** [comment]
P.S. this only happens if you cancel partway through onboarding (after giving the external ID twice) and then quit and restart the app; until then it has the decrypted SBBStudyParticipant in its in-memory cache and doesn't need the credentials to decrypt it.

**Comment by syoung-smallwisdom** [comment]
Closing. haven't run into the issue in a while.

**Pull request closed without merging**
