### PR TITLE
mood_survey_bug

### PR DESCRIPTION
**Pull request by dephillipsmichael**
Fix bug where pre-populating mood survey was one off

### CODE REVIEW

**Review by syoung-smallwisdom — CHANGES_REQUESTED** [review]
I believe that the bug is setting the value at 0. Please verify what scale is used by ResearchKit and look at updating the server-based survey. Thanks.

**Comment by dephillipsmichael** [comment]
@syoung-smallwisdom can you elaborate? I'm not really following that the bug is setting the value at 0.  The bug is easily reproducible by doing on question on the daily check in, and then pressing back.  You will see the answer on that screen is one off.

**Comment by syoung-smallwisdom** [comment]
Can you please assign the ticket to me and I will take a look. Thanks!

**Comment by syoung-smallwisdom** [comment]
Thanks for bringing this to my attention. Unfortunately, the fix for this requires allowing the mood scale questions to be a different result type so that the server will get the correct result. Will require additional work at Journey PRO level to show in the dashboard. Sorry.

See https://github.com/Sage-Bionetworks/BridgeAppSDK/pull/293

Closing this PR.

**Pull request closed without merging**
