### PR TITLE
Change to support Elevate PR to move custom UI into BridgeAppSDK

### PR DESCRIPTION
**Pull request by joshbruhin**
These are changes to support this PR and should be merged at the same time: https://github.com/Sage-Bionetworks/elevateMS/pull/124

Change ‘SBAScheduledActivityManager’ to NOT supply the ‘generic’ view controller. Update ‘SBAUnderlinedButton’ to use the right style class for text color.

### CODE REVIEW

**Comment by joshbruhin** [comment]
@syoung-smallwisdom ping

**Comment by syoung-smallwisdom** [comment]
Could we please *not* do this right now. I don't want to risk effecting other projects and would prefer to stick with our original plan of overriding in at the app level. Thanks.

**Review by syoung-smallwisdom — CHANGES_REQUESTED** [review]
Please remove override to return a generic step view controller.

**Comment by joshbruhin** [comment]
@syoung-smallwisdom  Ugh, sorry, this was a mistake! Yes, I'll remove this.

**Comment by joshbruhin** [comment]
@syoung-smallwisdom change made. Can we merge this one and this one in Elevate: https://github.com/Sage-Bionetworks/elevateMS/pull/124

**Review by syoung-smallwisdom — APPROVED** [review]
looks good

**Pull request merged**
